### ISSUE TITLE
why is 400/30 is cero? 

### ISSUE THREAD

**Issue by picoshmit** [Rusketh/FML_Calculator#4] opened 2020-07-05 06:51 UTC
how im supose to divide?

**Comment by Rusketh** [comment] 2020-07-05 12:45
400/30 = 13.333333

![image](https://user-images.githubusercontent.com/1250854/86532880-0e8a4980-bec5-11ea-9d38-881713a14604.png)

Closed as unable to reproduce.

**Closed by Rusketh** 2020-07-05 12:45 UTC
Labels: No details

**Comment by Vassi** [comment] 2020-07-06 15:11
This also happened to me, specifically when you're doing a sequence.

I.e. 
15 * 200 
[click] =
[shows 3000]
/ 60 
[click] =
Shows 0.

On a normal calculator I expect to be able to act on the result of the last action, but for some reason that doesn't work sometimes.

**Comment by Rusketh** [comment] 2020-07-07 01:21
Oh, this is not a bug. After pressing equation it will display the answer but will then the current memory  will reset upon input immediately to 0, This is an intended feature not a bug.
How ever you can use right arrow to paste the previous equation value into the current memory, but that feature is experimental and may not work as intended. Something to note, if you try to use this feature, is that it pastes the value from the equation selected in history (use up/down to navigate).

**Comment by Vassi** [comment] 2020-07-08 04:28
I mean, it's your mod, but that is literally not how every calculator app I have access to works. Thanks for clarifying though so I don't think I'm crazy, I wasn't sure why sometimes I had 0 and sometimes I didn't. Maybe consider it a feature request to allow chaining.
